describe('Login', () => {
  it('login - success', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
    cy.get('.oxd-button').click()
    cy.url().should('include', '/web/index.php/dashboard/index')  
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers')
    cy.get('.oxd-main-menu-search > .oxd-input').type('PIM')
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewEmployeeList')
    cy.get(':nth-child(2) > .oxd-input').type('0427')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.get('.oxd-button--ghost').click()
    cy.get(':nth-child(2) > .oxd-input').type('9999')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
    cy.get('.orangehrm-header-container > .oxd-button').click()
    cy.get('.--name-grouped-field > :nth-child(1) > :nth-child(2) > .oxd-input').type('Thiago')
    cy.get(':nth-child(2) > :nth-child(2) > .oxd-input').type('Andrade')
    cy.get(':nth-child(3) > :nth-child(2) > .oxd-input').type('Lima')
    cy.get('.oxd-grid-item > .oxd-input-group > :nth-child(2) > .oxd-input').type('321545')
    cy.get('.oxd-switch-input').click()
    cy.get(':nth-child(4) > .oxd-grid-2 > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('kbca122')
    cy.get('.user-password-cell > .oxd-input-group > :nth-child(2) > .oxd-input').type('158246Ab')
    cy.get('.oxd-grid-2 > :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('158246Ab')
    cy.get('.oxd-button--secondary').click()
    cy.get(':nth-child(2) > .oxd-main-menu-item').click()
    cy.get(':nth-child(2) > .oxd-input').type('0379321545')
    cy.get('.oxd-form-actions > .oxd-button--secondary').click()
  })
})
